image: maven:latest

stages:
  - build
  - test
  - code-quality
  - deploy

variables:
  RULES_CHANGES_PATH: "**/*"

.base-rules:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - $RULES_CHANGES_PATH
    - when: manual
      allow_failure: false

.backend:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "backend/**/*"

.frontend:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "frontend/**/*"

frontend-build:
  image: node:16-alpine
  stage: build
  extends: .frontend
  needs: []
  script:
    - echo "building the frontend code..."
    - cd frontend
    - yarn install
    - yarn build


build-backend:
  stage: build
  extends: .backend
  needs: []
  script:
    - cd backend
    - mvn clean compile

test-backend:
  stage: test
  extends: .backend
  needs: ["build-backend"]
  script:
    - cd backend
    - mvn clean test -Dspring.profiles.active=test

frontend-test:
  stage: test
  image: node:16-alpine
  extends: .frontend
  needs: ["frontend-build"]
  before_script:
    - apk add chromium
    - export CHROME_BIN=/usr/bin/chromium-browser
  script:
    - echo "Testing the frontend code..."
    - cd frontend
    - yarn install
    - yarn test

backend-staging:
   image: ruby:latest
   stage: deploy
   before_script:
     - cd backend
     - apt-get update -qy
     - apt-get install -y ruby-dev
     - gem install dpl
   script:
     - dpl --provider=heroku --app=wanderergroup21 --api-key=$HEROKU_STAGING_API_KEY_BACKEND
   only:
     - develop

frontend-staging:
  stage: deploy
  image: ruby:latest
  needs: ["backend-staging"]
  before_script:
    - cd frontend
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - dpl --provider=heroku --app=wanderergroup21frontend --api-key=$HEROKU_STAGING_API_KEY_BACKEND
  only:
    - develop

backend-code-quality:
  stage: code-quality
  image: maven:3-jdk-11
  variables:
    UPLOAD_QUALITY_REPORT: 'curl -X PUT -H "Authorization: Token $QSCORED_API_KEY" + -H "username:patel.janvi23798@gmail.com" -H "Content-Type: application/xml" --url "https://qscored.com/api/upload/file.xml?is_open_access=off&version=$CI_PIPELINE_IID&project_name=wanderer_backend" -F "file=@DesigniteAnalysis.xml"'
  before_script:
    - cd backend
    - apt-get update
    - apt-get install -y wget curl
    - wget -O DesigniteJava.jar https://www.dropbox.com/s/mwizkj8uhplz4x3/DesigniteJava.jar?dl=1
  script:
    - java -jar DesigniteJava.jar -i ./ -o code-quality/ -f XML
    - ls -l
    - ls code-quality
    - cd code-quality
    - eval "$UPLOAD_QUALITY_REPORT"
    - echo "$UPLOAD_QUALITY_REPORT"
  only:
    - develop